'use client';

import { motion } from 'framer-motion';
import { useState } from 'react';

interface ConceptualFrameworkProps {
  locale?: 'en' | 'ko';
  example?: {
    researchQuestion: string;
    variables: {
      independent: string[];
      mediators: string[];
      dependent: string[];
    };
    theoreticalFramework: string;
    tScore: number;
  };
}

// T-Score color based on value
function getTScoreColor(score: number): string {
  if (score >= 0.8) return '#ff3366';  // modal
  if (score >= 0.6) return '#ff8844';  // typical
  if (score >= 0.4) return '#ffcc22';  // balanced
  if (score >= 0.2) return '#44ffaa';  // creative
  return '#22bbff';  // divergent
}

function getTScoreLabel(score: number, locale: 'en' | 'ko'): string {
  if (score >= 0.8) return locale === 'ko' ? '모달' : 'Modal';
  if (score >= 0.6) return locale === 'ko' ? '전형적' : 'Typical';
  if (score >= 0.4) return locale === 'ko' ? '균형' : 'Balanced';
  if (score >= 0.2) return locale === 'ko' ? '창의적' : 'Creative';
  return locale === 'ko' ? '발산적' : 'Divergent';
}

export function ConceptualFramework({ locale = 'en', example }: ConceptualFrameworkProps) {
  const [hoveredVariable, setHoveredVariable] = useState<string | null>(null);

  // Default example for AI in Education
  const data = example || {
    researchQuestion: 'How does AI-powered adaptive tutoring influence the development of metacognitive skills in undergraduate students?',
    variables: {
      independent: ['AI Tutoring Intervention', 'Personalization Level', 'Feedback Frequency'],
      mediators: ['Metacognitive Awareness', 'Self-Monitoring', 'Strategy Selection'],
      dependent: ['Learning Outcomes', 'Transfer Ability', 'Autonomous Learning']
    },
    theoreticalFramework: 'Integrated Self-Regulated Learning & Cognitive Load Theory',
    tScore: 0.42
  };

  const tScoreColor = getTScoreColor(data.tScore);
  const tScoreLabel = getTScoreLabel(data.tScore, locale);

  return (
    <div className="space-y-8">
      {/* Header with T-Score */}
      <div className="flex items-center justify-between">
        <div>
          <span className="font-mono text-micro uppercase tracking-widest text-stellar-faint">
            A6 Conceptual Framework Visualizer
          </span>
          <h3 className="mt-2 void-heading-3 text-stellar-core">
            {locale === 'ko' ? '교육에서의 AI: 개념적 프레임워크' : 'AI in Education: Conceptual Framework'}
          </h3>
        </div>
        <div className="flex items-center gap-3 px-4 py-2 void-card border-l-4" style={{ borderLeftColor: tScoreColor }}>
          <span className="font-mono text-micro text-stellar-dim">T-Score</span>
          <span className="font-mono text-body-lg font-bold" style={{ color: tScoreColor }}>
            {data.tScore.toFixed(2)}
          </span>
          <span className="text-micro px-2 py-1" style={{ backgroundColor: `${tScoreColor}20`, color: tScoreColor }}>
            {tScoreLabel}
          </span>
        </div>
      </div>

      {/* Research Question */}
      <div className="void-card p-6">
        <span className="void-label text-stellar-dim mb-2 block">
          {locale === 'ko' ? '연구 질문' : 'Research Question'}
        </span>
        <p className="text-body-lg text-stellar-bright italic">
          "{data.researchQuestion}"
        </p>
      </div>

      {/* Theoretical Framework */}
      <div className="void-card p-6 border-l-4" style={{ borderLeftColor: tScoreColor }}>
        <span className="void-label text-stellar-dim mb-2 block">
          {locale === 'ko' ? '이론적 프레임워크' : 'Theoretical Framework'}
        </span>
        <p className="text-body text-stellar-core font-medium">
          {data.theoreticalFramework}
        </p>
        <p className="mt-2 text-caption text-stellar-dim">
          {locale === 'ko'
            ? 'T-0.42 (창의적 범위) - 전형적인 TAM (T-0.92)보다 더 참신한 접근'
            : 'T-0.42 (Creative Range) - More novel approach than typical TAM (T-0.92)'}
        </p>
      </div>

      {/* Visual Framework Diagram */}
      <div className="void-terminal overflow-hidden">
        <div className="void-terminal-header">
          <div className="flex items-center gap-2">
            <div className="void-terminal-dot void-terminal-dot-red" />
            <div className="void-terminal-dot void-terminal-dot-yellow" />
            <div className="void-terminal-dot void-terminal-dot-green" />
          </div>
          <span className="text-micro text-stellar-faint ml-4">
            {locale === 'ko' ? '개념적_프레임워크.svg' : 'conceptual_framework.svg'}
          </span>
          <span className="ml-auto text-micro text-tscore-creative">
            Generated by A6 + Nano Banana
          </span>
        </div>

        <div className="p-8 bg-void-deep">
          {/* SVG Conceptual Framework Visualization */}
          <svg viewBox="0 0 900 400" className="w-full h-auto">
            {/* Definitions */}
            <defs>
              <linearGradient id="arrowGrad" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" stopColor="#44ffaa" stopOpacity="0.3" />
                <stop offset="100%" stopColor="#44ffaa" stopOpacity="0.8" />
              </linearGradient>
              <filter id="glow">
                <feGaussianBlur stdDeviation="3" result="coloredBlur" />
                <feMerge>
                  <feMergeNode in="coloredBlur" />
                  <feMergeNode in="SourceGraphic" />
                </feMerge>
              </filter>
              <marker id="arrowhead" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
                <polygon points="0 0, 10 3.5, 0 7" fill="#44ffaa" />
              </marker>
            </defs>

            {/* Background Grid */}
            <g opacity="0.1">
              {[...Array(18)].map((_, i) => (
                <line key={`v${i}`} x1={i * 50} y1="0" x2={i * 50} y2="400" stroke="#8888aa" strokeWidth="0.5" />
              ))}
              {[...Array(8)].map((_, i) => (
                <line key={`h${i}`} x1="0" y1={i * 50} x2="900" y2={i * 50} stroke="#8888aa" strokeWidth="0.5" />
              ))}
            </g>

            {/* Connection Arrows */}
            <g>
              {/* Independent → Mediators */}
              {data.variables.independent.map((_, i) => (
                <motion.line
                  key={`im${i}`}
                  x1="230" y1={100 + i * 100}
                  x2="320" y2={100 + i * 100}
                  stroke="url(#arrowGrad)"
                  strokeWidth="2"
                  markerEnd="url(#arrowhead)"
                  initial={{ pathLength: 0 }}
                  animate={{ pathLength: 1 }}
                  transition={{ delay: 0.5 + i * 0.1, duration: 0.5 }}
                />
              ))}
              {/* Mediators → Dependent */}
              {data.variables.mediators.map((_, i) => (
                <motion.line
                  key={`md${i}`}
                  x1="580" y1={100 + i * 100}
                  x2="670" y2={100 + i * 100}
                  stroke="url(#arrowGrad)"
                  strokeWidth="2"
                  markerEnd="url(#arrowhead)"
                  initial={{ pathLength: 0 }}
                  animate={{ pathLength: 1 }}
                  transition={{ delay: 0.8 + i * 0.1, duration: 0.5 }}
                />
              ))}
              {/* Cross connections (dotted) */}
              <motion.path
                d="M 450 120 Q 500 200 450 280"
                stroke="#22bbff"
                strokeWidth="1"
                strokeDasharray="4,4"
                fill="none"
                initial={{ pathLength: 0 }}
                animate={{ pathLength: 1 }}
                transition={{ delay: 1.2, duration: 0.8 }}
              />
            </g>

            {/* Independent Variables (Left) */}
            <g>
              <text x="130" y="35" fill="#22bbff" fontSize="12" fontFamily="monospace" textAnchor="middle">
                {locale === 'ko' ? '독립변수' : 'INDEPENDENT'}
              </text>
              {data.variables.independent.map((variable, i) => (
                <motion.g
                  key={`iv${i}`}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.2 + i * 0.1 }}
                  onMouseEnter={() => setHoveredVariable(variable)}
                  onMouseLeave={() => setHoveredVariable(null)}
                  style={{ cursor: 'pointer' }}
                >
                  <rect
                    x="30" y={70 + i * 100}
                    width="200" height="60"
                    fill={hoveredVariable === variable ? '#22bbff15' : '#0a0a0f'}
                    stroke="#22bbff"
                    strokeWidth={hoveredVariable === variable ? 2 : 1}
                    rx="4"
                    filter={hoveredVariable === variable ? 'url(#glow)' : undefined}
                  />
                  <text
                    x="130" y={108 + i * 100}
                    fill="#22bbff"
                    fontSize="13"
                    fontFamily="system-ui"
                    textAnchor="middle"
                    fontWeight="500"
                  >
                    {variable}
                  </text>
                </motion.g>
              ))}
            </g>

            {/* Mediators (Center) */}
            <g>
              <text x="450" y="35" fill="#ffcc22" fontSize="12" fontFamily="monospace" textAnchor="middle">
                {locale === 'ko' ? '매개변수' : 'MEDIATORS'}
              </text>
              {data.variables.mediators.map((variable, i) => (
                <motion.g
                  key={`mv${i}`}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.4 + i * 0.1 }}
                  onMouseEnter={() => setHoveredVariable(variable)}
                  onMouseLeave={() => setHoveredVariable(null)}
                  style={{ cursor: 'pointer' }}
                >
                  <rect
                    x="330" y={70 + i * 100}
                    width="240" height="60"
                    fill={hoveredVariable === variable ? '#ffcc2215' : '#0a0a0f'}
                    stroke="#ffcc22"
                    strokeWidth={hoveredVariable === variable ? 2 : 1}
                    rx="4"
                    filter={hoveredVariable === variable ? 'url(#glow)' : undefined}
                  />
                  <text
                    x="450" y={108 + i * 100}
                    fill="#ffcc22"
                    fontSize="13"
                    fontFamily="system-ui"
                    textAnchor="middle"
                    fontWeight="500"
                  >
                    {variable}
                  </text>
                </motion.g>
              ))}
            </g>

            {/* Dependent Variables (Right) */}
            <g>
              <text x="770" y="35" fill="#44ffaa" fontSize="12" fontFamily="monospace" textAnchor="middle">
                {locale === 'ko' ? '종속변수' : 'DEPENDENT'}
              </text>
              {data.variables.dependent.map((variable, i) => (
                <motion.g
                  key={`dv${i}`}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.6 + i * 0.1 }}
                  onMouseEnter={() => setHoveredVariable(variable)}
                  onMouseLeave={() => setHoveredVariable(null)}
                  style={{ cursor: 'pointer' }}
                >
                  <rect
                    x="680" y={70 + i * 100}
                    width="180" height="60"
                    fill={hoveredVariable === variable ? '#44ffaa15' : '#0a0a0f'}
                    stroke="#44ffaa"
                    strokeWidth={hoveredVariable === variable ? 2 : 1}
                    rx="4"
                    filter={hoveredVariable === variable ? 'url(#glow)' : undefined}
                  />
                  <text
                    x="770" y={108 + i * 100}
                    fill="#44ffaa"
                    fontSize="13"
                    fontFamily="system-ui"
                    textAnchor="middle"
                    fontWeight="500"
                  >
                    {variable}
                  </text>
                </motion.g>
              ))}
            </g>

            {/* Theoretical Framework Label */}
            <motion.g
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1.5 }}
            >
              <rect
                x="250" y="350"
                width="400" height="40"
                fill="#0a0a0f"
                stroke={tScoreColor}
                strokeWidth="1"
                strokeDasharray="4,4"
                rx="4"
              />
              <text
                x="450" y="375"
                fill={tScoreColor}
                fontSize="12"
                fontFamily="monospace"
                textAnchor="middle"
              >
                {data.theoreticalFramework} (T-{data.tScore.toFixed(2)})
              </text>
            </motion.g>

            {/* A6 Badge */}
            <motion.g
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 1.8 }}
            >
              <rect x="20" y="350" width="80" height="30" fill="#44ffaa20" stroke="#44ffaa" rx="4" />
              <text x="60" y="370" fill="#44ffaa" fontSize="11" fontFamily="monospace" textAnchor="middle">
                A6 Output
              </text>
            </motion.g>
          </svg>
        </div>
      </div>

      {/* Variable Details */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="void-card p-5 border-t-2" style={{ borderTopColor: '#22bbff' }}>
          <h4 className="font-mono text-caption uppercase tracking-wider mb-3" style={{ color: '#22bbff' }}>
            {locale === 'ko' ? '독립변수' : 'Independent Variables'}
          </h4>
          <ul className="space-y-2">
            {data.variables.independent.map((v, i) => (
              <li key={i} className="flex items-center gap-2 text-caption text-stellar-bright">
                <span className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: '#22bbff' }} />
                {v}
              </li>
            ))}
          </ul>
        </div>

        <div className="void-card p-5 border-t-2" style={{ borderTopColor: '#ffcc22' }}>
          <h4 className="font-mono text-caption uppercase tracking-wider mb-3" style={{ color: '#ffcc22' }}>
            {locale === 'ko' ? '매개변수' : 'Mediating Variables'}
          </h4>
          <ul className="space-y-2">
            {data.variables.mediators.map((v, i) => (
              <li key={i} className="flex items-center gap-2 text-caption text-stellar-bright">
                <span className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: '#ffcc22' }} />
                {v}
              </li>
            ))}
          </ul>
        </div>

        <div className="void-card p-5 border-t-2" style={{ borderTopColor: '#44ffaa' }}>
          <h4 className="font-mono text-caption uppercase tracking-wider mb-3" style={{ color: '#44ffaa' }}>
            {locale === 'ko' ? '종속변수' : 'Dependent Variables'}
          </h4>
          <ul className="space-y-2">
            {data.variables.dependent.map((v, i) => (
              <li key={i} className="flex items-center gap-2 text-caption text-stellar-bright">
                <span className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: '#44ffaa' }} />
                {v}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Nano Banana Note */}
      <div className="flex items-center gap-4 p-4 void-card border-l-4 border-tscore-creative">
        <div className="w-10 h-10 rounded-full bg-tscore-creative/20 flex items-center justify-center">
          <span className="text-lg">🍌</span>
        </div>
        <div>
          <p className="text-caption text-stellar-bright">
            {locale === 'ko'
              ? 'Nano Banana 이미지 합성으로 생성됨 (Gemini 3 Pro Image)'
              : 'Generated with Nano Banana Image Synthesis (Gemini 3 Pro Image)'}
          </p>
          <p className="text-micro text-stellar-dim mt-1">
            {locale === 'ko'
              ? 'A6 에이전트가 연구 맥락을 분석하고 자동으로 개념적 프레임워크를 시각화합니다'
              : 'A6 agent analyzes research context and automatically visualizes the conceptual framework'}
          </p>
        </div>
      </div>
    </div>
  );
}
